update readme
axonivy-market/process-analyser pull request #58
Opened 2024-11-26 04:58 UTC by ntqdinh-axonivy

2024-11-26 07:42 UTC, ivy-sgi commented
Please add the following sentence somewhere:  Include a task or a task switch element aftern an alternative.

2024-11-26 08:10 UTC, ivy-sgi commented
Hi @ntqdinh-axonivy  Please use the standard logo: 
![image](https://github.com/user-attachments/assets/2f47f97d-e16e-4377-94e5-cfe40ffaa1f1)

2024-11-27 02:08 UTC, ntqdinh-axonivy commented
Hi @ivy-sgi 
I have updated the readme with more hints about setup steps and images of the process analyzer's diagram in the latest version.
Could you have a quick look and help us with the German translation for readme file?
Thanks

(I will update the logo in Axon Ivy market PR later.)

2024-11-28 08:21 UTC, phhung-axonivy requested changes
LGTM

2024-11-28 08:21 UTC, phhung-axonivy commented on process-analyser-product/README.md
> +![show statistic demo](show-statistic.gif)
Could you please create a new folder 'images' and move all images to that folder?
Afterthat update the README (DE) files.

2024-11-28 08:38 UTC, phhung-axonivy approved these changes
LGTM

2024-11-28 08:39 UTC, merged